In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime as dt, date

In [4]:
hospital_data = pd.read_excel('HospitalDatabase.xlsx')
hospital_data.tail()

PatientID FirstName  LastName             DateOfBirth Gender  \
940        941       Wat   Fideler 1986-05-26 00:01:19.761   Male   
941        942    Wandie  Baythrop 1970-06-10 21:41:03.814   Male   
942        943   Diahann   Smeeton 1983-01-08 21:49:27.884   Male   
943        944  Panchito   Sharple 1963-06-05 07:57:05.569   Male   
944        945     Walsh    Calvie 1972-08-06 03:40:03.454   Male   

                       Race Language  
940  Black/African-American  English  
941  Black/African-American  English  
942  Black/African-American  English  
943  Black/African-American  English  
944  Black/African-American  English

# 61.np.arange(1,31).reshape(6,5) Find the array slicing to get the elements with values 11,12,16,17.

In [5]:
numbers = np.arange(1,31)
numbers = numbers.reshape(6,5)
print(numbers)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [6]:
print(numbers[2:4,0:2])

[[11 12]
 [16 17]]


In [7]:
result = numbers[[2,2,3,3],[0,1,0,1]]
print(result)

[11 12 16 17]


# 62.Create a dataframe with acuity and EDDisposition as the indices and the count of number of patients as the value.

In [8]:
df = pd.read_excel('HospitalDatabase.xlsx','EDVisits')

df = pd.DataFrame(df, columns=['EDDisposition','Acuity'])

df.reset_index().groupby( [ "EDDisposition", "Acuity"],as_index=False ).count()



EDDisposition  Acuity  index
0      Admitted       1     32
1      Admitted       2    116
2      Admitted       3     81
3      Admitted       4    107
4      Admitted       5    179
5    Discharged       1    558
6    Discharged       2     66
7    Discharged       4     30
8    Discharged       5     30

# 63.List male patients over the age of 60 who have undergone surgery from January-March 2019.

In [29]:
from datetime import datetime, date
df = pd.read_excel('HospitalDatabase.xlsx','Patients')
print(df)


     PatientID FirstName  LastName             DateOfBirth Gender  \
0            1     Lanni       Sue 1960-01-01 00:00:00.000   Male   
1            2       Far     Myers 1985-11-15 02:08:42.090   Male   
2            3   Devlin    Michael 1976-04-15 02:52:09.762   Male   
3            4   Carmine     Texas 1968-10-15 03:32:13.635   Male   
4            5     Tann       Bama 1962-05-01 19:12:58.950   Male   
..         ...       ...       ...                     ...    ...   
940        941       Wat   Fideler 1986-05-26 00:01:19.761   Male   
941        942    Wandie  Baythrop 1970-06-10 21:41:03.814   Male   
942        943   Diahann   Smeeton 1983-01-08 21:49:27.884   Male   
943        944  Panchito   Sharple 1963-06-05 07:57:05.569   Male   
944        945     Walsh    Calvie 1972-08-06 03:40:03.454   Male   

                       Race Language  
0                     White  English  
1                     White  English  
2                     White  English  
3              

In [30]:
df.DateOfBirth

0     1960-01-01 00:00:00.000
1     1985-11-15 02:08:42.090
2     1976-04-15 02:52:09.762
3     1968-10-15 03:32:13.635
4     1962-05-01 19:12:58.950
                ...          
940   1986-05-26 00:01:19.761
941   1970-06-10 21:41:03.814
942   1983-01-08 21:49:27.884
943   1963-06-05 07:57:05.569
944   1972-08-06 03:40:03.454
Name: DateOfBirth, Length: 945, dtype: datetime64[ns]

# 64.Create a dataframe by splitting provider name to firstname and lastname with names for the columns.

In [85]:
df = pd.read_excel('HospitalDatabase.xlsx','Providers')

df = pd.DataFrame(df, columns=['ProviderName'])



# 65.